/*
 * Copyright 2019 Lane W. Surface
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jtxt.emulator.tui;

/**
 * In order to receive notification of events which are generated by the terminal and
 * routed to TUI components, a class must implement this interface and pass itself
 * into an appropriate method for registering itself with a {@code Component} that it
 * wishes to listen to.
 */
@FunctionalInterface
public interface Callable {
  /**
   * The method which is invoked when an event is generated by the Component with
   * witch this class is registered.
   */
  void dispatch();
}
